-- AlterTable
ALTER TABLE "production_batches" ADD COLUMN     "anyRemarks" TEXT,
ADD COLUMN     "billingRemarks" TEXT,
ADD COLUMN     "bulkQcRemarks" TEXT,
ADD COLUMN     "bulkQcStatus" TEXT,
ADD COLUMN     "currentStageId" "CombinedLotStageId" NOT NULL DEFAULT 'IPQC',
ADD COLUMN     "dispatchDate" TIMESTAMP(3),
ADD COLUMN     "dispatchedQty" DOUBLE PRECISION,
ADD COLUMN     "ewayBillDate" TIMESTAMP(3),
ADD COLUMN     "ewayBillNo" TEXT,
ADD COLUMN     "invoiceDate" TIMESTAMP(3),
ADD COLUMN     "invoiceNo" TEXT,
ADD COLUMN     "ipqcRemarks" TEXT,
ADD COLUMN     "ipqcStatus" TEXT,
ADD COLUMN     "mfgApprovedQty" DOUBLE PRECISION,
ADD COLUMN     "mfgQaStatus" TEXT,
ADD COLUMN     "mfgQcStatus" TEXT,
ADD COLUMN     "mfgRejectedQty" DOUBLE PRECISION,
ADD COLUMN     "mfgRemarks" TEXT,
ADD COLUMN     "mfgWastageQty" DOUBLE PRECISION,
ADD COLUMN     "packApprovedQty" DOUBLE PRECISION,
ADD COLUMN     "packQaStatus" TEXT,
ADD COLUMN     "packQcStatus" TEXT,
ADD COLUMN     "packRejectedQty" DOUBLE PRECISION,
ADD COLUMN     "packRemarks" TEXT,
ADD COLUMN     "packWastageQty" DOUBLE PRECISION,
ADD COLUMN     "packagingEndDate" TIMESTAMP(3),
ADD COLUMN     "packagingRemarks" TEXT,
ADD COLUMN     "packagingStartDate" TIMESTAMP(3),
ADD COLUMN     "packagingStatus" TEXT,
ADD COLUMN     "remainingQty" DOUBLE PRECISION,
ADD COLUMN     "shipperQty" DOUBLE PRECISION,
ADD COLUMN     "totalShipperWeight" DOUBLE PRECISION,
ADD COLUMN     "transportType" TEXT;
